/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/basegun1.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/basegun1.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.003, -0.022, 0.022]} rotation={[-2.749, 1.569, 1.178]}>
        <mesh geometry={nodes.Mesh_11.geometry} material={materials['black metal.001']} />
        <mesh geometry={nodes.Mesh_11_1.geometry} material={materials.grip} />
      </group>
      <mesh geometry={nodes['右拇指保險-1'].geometry} material={materials['silver metal']} position={[0.003, -0.023, 0.022]} rotation={[1.916, 0, 1.569]} />
      <mesh geometry={nodes['準心光纖-1001'].geometry} material={materials['color-11']} position={[0, 0.013, -0.115]} rotation={[0, 0, 2.15]} />
      <mesh geometry={nodes['準心座-1001'].geometry} material={materials['black metal.001']} position={[0.002, 0.019, -0.1]} rotation={[1.571, 0, Math.PI / 2]} />
      <mesh geometry={nodes['照門飛機座螺絲-1001'].geometry} material={materials['black metal']} position={[0, 0.01, 0.054]} rotation={[0, -1.436, 0]} />
      <mesh geometry={nodes['飛機座尾部固定螺絲-1'].geometry} material={materials['light grey high gloss plastic']} position={[0, 0.001, 0.065]} rotation={[-1.571, -0.392, Math.PI / 2]} />
      <mesh geometry={nodes['擊錘連桿咬花PIN-1'].geometry} material={materials.Material_0} position={[-0.003, -0.018, 0.075]} rotation={[-1.4, Math.PI / 2, 0]} />
      <mesh geometry={nodes['擊錘簧座_預設stp-1'].geometry} material={materials['black metal.041']} position={[-0.099, -0.031, 0.059]} rotation={[-1.886, 0, 0]} />
      <mesh geometry={nodes.滑套.geometry} material={materials['black metal.002']} position={[0.003, -0.022, 0.022]} rotation={[0, 0, -3.133]} />
      <mesh geometry={nodes.照門.geometry} material={materials['black metal']} position={[0.003, -0.022, 0.022]} rotation={[-1.571, 0.008, -1.57]} />
    </group>
  )
}

useGLTF.preload('/basegun1.glb')
